version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3001:3001" 
    environment:
      - DATABASE_URL=postgresql://root:root@host.docker.internal:5432/dreamvacations
      - COUNTRIES_API_BASE_URL=https://restcountries.com/v3.1
