apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Jvb3Q6cm9vdEAxOTIuMTY4LjEwMC4xMDQ6NTQzMi9kcmVhbXZhY2F0aW9ucw==
  COUNTRIES_API_BASE_URL: aHR0cHM6Ly9yZXN0Y291bnRyaWVzLmNvbS92My4x