apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gidoiualexandru/dream-vacation-app-frontend:dev
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: frontend-secrets
          env:
            - name: NODE_OPTIONS
              value: "--openssl-legacy-provider"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  selector:
    app: frontend
  ports:
    - name: frontend-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
